// tslint:disable
/**
 * Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: johan@johanbaskovec.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    User,
} from './';

/**
 * @export
 * @interface ArticleAllOf
 */
export interface ArticleAllOf {
    /**
     * @type {string}
     * @memberof ArticleAllOf
     */
    title: string;
    /**
     * @type {string}
     * @memberof ArticleAllOf
     */
    content: string;
    /**
     * @type {User}
     * @memberof ArticleAllOf
     */
    author: User;
    /**
     * @type {number}
     * @memberof ArticleAllOf
     */
    version: number;
}
