// tslint:disable
/**
 * Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: johan@johanbaskovec.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ArticleCreationRequest
 */
export interface ArticleCreationRequest {
    /**
     * @type {string}
     * @memberof ArticleCreationRequest
     */
    id: string;
    /**
     * @type {string}
     * @memberof ArticleCreationRequest
     */
    title: string;
    /**
     * @type {string}
     * @memberof ArticleCreationRequest
     */
    content: string;
}
