// tslint:disable
/**
 * Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: johan@johanbaskovec.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Authorization,
} from './';

/**
 * @export
 * @interface User
 */
export interface User {
    /**
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * @type {number}
     * @memberof User
     */
    lastModificationTime?: number;
    /**
     * @type {number}
     * @memberof User
     */
    creationTime?: number;
    /**
     * @type {string}
     * @memberof User
     */
    password?: string | null;
    /**
     * @type {number}
     * @memberof User
     */
    version: number;
    /**
     * @type {Array<Authorization>}
     * @memberof User
     */
    authorizations?: Array<Authorization>;
}
