// tslint:disable
/**
 * Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: johan@johanbaskovec.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Role,
} from './';

/**
 * @export
 * @interface UserAllOf
 */
export interface UserAllOf {
    /**
     * @type {string}
     * @memberof UserAllOf
     */
    username: string;
    /**
     * @type {string}
     * @memberof UserAllOf
     */
    password?: string | null;
    /**
     * @type {number}
     * @memberof UserAllOf
     */
    version: number;
    /**
     * @type {Array<Role>}
     * @memberof UserAllOf
     */
    roles?: Array<Role>;
}
