// tslint:disable
/**
 * Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: johan@johanbaskovec.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface WebSocketMessage
 */
export interface WebSocketMessage {
    /**
     * @type {string}
     * @memberof WebSocketMessage
     */
    type: WebSocketMessageTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum WebSocketMessageTypeEnum {
    WebSocketClientChatMessage = 'WebSocketClientChatMessage',
    WebSocketServerChatMessage = 'WebSocketServerChatMessage'
}

